name: "[CI] Continuous Integration"

# Whenever there's a push, pull request opened, or pull request synchronized
on:
  push: {}
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      ## [Common CI Steps]
      - uses: actions/checkout@v3
      ## =================

      - name: "Install Node.js (latest stable)"
        uses: actions/setup-node@v3
        with:
          node-version: 'node'  # Installs the latest stable version

      - name: "Install Dependencies"
        run: npm install

      - name: "Lint"
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16-chrome109  # Latest Cypress image with a compatible Node.js version
    steps:
      ## [Common CI Steps]
      - uses: actions/checkout@v3
      ## =================

      - name: "Install Dependencies"
        run: npm install

      - name: "Test - Cypress"
        run: npm run test
